= Reactor 3 参考指南

作者：Stephane Maldini @smaldini Simon Baslé @simonbasle

译者：quxinyong@qq.com

头条号： https://www.toutiao.com/c/user/3662984752/#mid=1640272215305230[IT荠荠菜]

软件版本：3.2.11.RELEASE

[[about-doc]]
= 关于文档
:linkattrs:

本节简要概述 Reactor 参考指南。你不必按顺序阅读本指南。尽管章节之间有引用关联，但它们的内容都是独立的。

== 最新版本、版权声明
Reactor 参考指南作为 HTML 文档提供。最新版：https://projectreactor.io/docs/core/release/reference/docs/index.html

文档副本可供你自己使用及分发给其他人，必须免费提供。此外，不论以印刷品或电子方式分发，每份文档副本要包含版权声明。

== 做贡献
本指南是用
https://asciidoctor.org/docs/asciidoc-writers-guide/[Asciidoc]
格式编写的。
原始文档：
https://github.com/reactor/reactor-core/tree/master/docs/asciidoc.

如果你认为文档有需要改善的地方，可以到 GitHub 去拉取一个分支，修改后提交合并请求即可！

建议你检出仓库的本地副本，以便你可以使用 `asciidoctor` 生成文档并检查呈现。有些章节依赖于包含的文件，因此 GitHub 呈现并不总是完整的。

ifeval::["{backend}" == "html5"]
TIP: 为了方便文档编辑，大多数章节的末尾都有一个链接，该链接直接在GitHub上打开一个编辑界面，以编辑相应章节。这些链接只出现在本指南的 HTML5 版本中。它们看起来像下面的对<<about-doc>>的link:https://github.com/reactor/reactor-core/edit/master/docs/asciidoc/aboutDoc.adoc[建议编辑^, role="fa fa-edit"]。
endif::[]

== 帮助
有以下几种方式：

* 与 https://gitter.im/reactor/reactor[Gitter] 上的社区取得联系。.
* 在网站 stackoverflow.com 上，向 https://stackoverflow.com/tags/project-reactor[`project-reactor`] 提问。
* 在 GitHub 上报告 bugs。下面的仓库受到密切监视：
https://github.com/reactor/reactor-core/issues[reactor-core]（包含基本功能）和
https://github.com/reactor/reactor-addons/issues[reactor-addons]（包含测试、适配器问题）。

NOTE: 所有 Reactor 代码都是开源的，也link:https://github.com/reactor/reactor-core/tree/master/docs/asciidoc[包括相应的文档]。如果你发现了文档的问题，或者只是想要改善它们，
请link:https://github.com/reactor/reactor-core/blob/master/CONTRIBUTING.md[加入]。

== 下一步
* 如果你想直接跳到代码部分，可以去<<getting-started>>章节。
* 但是，如果你对 _反应式编程_ 比较陌生，那么你可能应该从<<intro-reactive>>章节开始。
* 如果你熟悉 Reactor 概念，只是想寻找合适的工具，但不关心相关操作符，可以去附录：<<which-operator>>

* 想了解 Reactor 的更深的核心功能，请去<<core-features>>章节，可以学到：
** 更多关于 Reactor 的反应式类型包含在 “<<flux>>”和“<<mono>>”小节中。
** 如何使用调度器切换线程上下文。
** <<error.handling>>小节：如何处理错误。
* 单元测试？这也是可以的，请使用 `reactor-test` 项目。具体请看<<testing>>章节。
* <<producing>>提供了一种更高级的创建反应式源的方法。
* 其他高级主题包含在<<advanced>>章节中。